### PR TITLE
Add: Solution for Day 11, 12, 14 and 15 in Swift language. (for issue #49) 

### PR DESCRIPTION
**Pull request by ham118**
Add: Solution for Day 11, 12, 14 and 15 in Swift language. (for issue #49 )

### CODE REVIEW

**Comment by ham118** [comment]
@sagarchoudhary96 Please review this PR #96

**Comment by ham118** [comment]
> hey @ham118, i see changes for day 11,12,13,15 too in this PR request you to create a separate PR with changes for Day23 only.

Ok

**Comment by ham118** [comment]
@sagarchoudhary96 Please review this PR

**Comment by sagarchoudhary96** [comment]
@ham118  i reviewed and let comment `hey @ham118, i see changes for day 11,12,13,15 too in this PR request you to create a separate PR with changes for Day23 only.` create you to make required changes.

**Comment by ham118** [comment]
> @ham118 i see you created new PR will review it and close this one.

Thanks !!

**Pull request closed without merging**
