### PR TITLE
Add: Solution for Day 11, 12, 14 and 15 in Swift language.

### PR DESCRIPTION
**Pull request by ham118**
Add: Solution for Day 11, 12, 14 and 15 in Swift language.

### CODE REVIEW

**Comment by sagarchoudhary96** [comment]
@ham118 request you to update Commit message as per the Contribution Guidelines.you can go through this link: https://help.github.com/en/articles/changing-a-commit-message for reading about changing commit message. commit message can be `Add: Solution for Day 11 and Day 12 in Swift language`

**Comment by ham118** [comment]
@sagarchoudhary96 Please review this pull request

**Comment by ham118** [comment]
@sagarchoudhary96 Please review this pull request.

**Comment by sagarchoudhary96** [comment]
@ham118 day 13 is not available to solve in swift language on hackerrank, can you also confirm from your side too. you will need to just create PR with changes for Day 11,  Day12 , Day13. you can create separate PR for them. let me know will close this PR then accordingly and then you can update new one.

**Comment by ham118** [comment]
@sagarchoudhary96 I have verified a day 13 solution in XCode playground and it is working fine. Also, you can check with various book's title (string), author (string) and price (integer) values to put instead of 'readLine()!' function.

Although, If not consider day13 solution then I'll create PR with only day11,12,14 solutions in swift language and I'd like to add day15 solution in swift language. Please let me know so I can do accordingly.

**Comment by sagarchoudhary96** [comment]
@ham118, i would request to create PR for 11, 12, 14 and you can take day15 next to solve.

**Comment by ham118** [comment]
@sagarchoudhary96 Please check this PR and another separate PR will send you soon for day15 solution in swift language

**Comment by ham118** [comment]
Hi @sagarchoudhary96 Please review this pull request. As per our conversation removed day13 solution and added day15 solution in swift language.

**Comment by ham118** [comment]
> great work @ham118 👏

Thanks 👍

**Pull request merged**
