### PR TITLE
Rewritten solution.py in python3

### PR DESCRIPTION
**Pull request by rohit1636**

### CODE REVIEW

**Comment by sagarchoudhary96** [comment]
@rohit1636  I have added contributing guidelines in the repository. Request you to go through it and create new PR as per the guidelines. Closing This PR for now.

**Comment by rohit1636** [comment]
hey , I have made the changes according to your requirements i.e I did not change the main logic. I have changed only the syntax and create a new file for each day which consists code in python 3. Once check the previous pull request.Thanks.

**Comment by rohit1636** [comment]
Sorry , I didn't read the contributing guidelines.

**Comment by sagarchoudhary96** [comment]
@rohit1636  in most of the commit diff, it is showing whole file code as added instead of showing diff.  For. eg  the below one, the solution for this is already there and already running in python3.
Screenshot 2019-09-29 at 10 38 51 PM

**Comment by sagarchoudhary96** [comment]
also follow the contributing guideline, and then update PR accordingly. acc. to it a once max 4 days solution you can pick up to modify at once for a single PR and you need to tell about it in comments on the issue. once confirmed you can work on it. as it will help others to know which all has been already picked up and what all questions are opened and other can also get a chance to contribute.

**Comment by rohit1636** [comment]
Ok thanks. Sorry for disturbing these many times. I am contributing for the first time. Just learning it now.

**Comment by rohit1636** [comment]
I am busy traveling right now. So I will be sending PR by October 2.

**Comment by rohit1636** [comment]
I will be working on questions - 3,5,6,7. Update in the list so that others do not work on same questions. Thanks.

**Comment by sagarchoudhary96** [comment]
@rohit1636 ok sure , i'll assign those to you . Also i'm closing this PR ,you can raise a new PR for those solution once done

**Pull request closed without merging**
