### PR TITLE
Added Day 17 in Rust

### PR DESCRIPTION
**Pull request by Derek52**

### CODE REVIEW

**Comment by sagarchoudhary96** [comment]
@Derek52 I checked Day17 on hackerrank and it doesn't show an option for rust language to solve this problem.

**Comment by sagarchoudhary96** [comment]
can you pick another problem? looks like there is a limited number of problem that can be solved using rust.

**Comment by sagarchoudhary96** [comment]
let me know once will close this PR after your response.

**Comment by Derek52** [comment]
I'll look at other problems, go ahead and close this PR.

**Comment by sagarchoudhary96** [comment]
@Derek52 okay, just make sure to check if the option to solve in rust is present for the problem you are picking up on hackerrank. also let me know the problems for which the option is not available when you go through thee questions.

**Pull request closed without merging**
