### PR TITLE
Add:Day 22 solution in swift language

### PR DESCRIPTION
**Pull request by saurabh-7777**
this is for issue #49 .

### CODE REVIEW

**Comment by sagarchoudhary96** [comment]
@saurabh-7777 request you to fix above issue

**Comment by sagarchoudhary96** [comment]
@saurabh-7777 request you to check it.

**Comment by saurabh-7777** [comment]
@sagarchoudhary96  I have changed please review it.

**Comment by sagarchoudhary96** [comment]
@saurabh-7777 your previous solution was just missing `root:` label in function call, you just need to put this line as return statement in `getHeight` function:
```
 return root == nil ? -1 : 1 + max(getHeight(root: root!.left), getHeight(root: root!.right))
```

request you to update will this solution.

**Comment by sagarchoudhary96** [comment]
@saurabh-7777 any updates?

**Comment by sagarchoudhary96** [comment]
@saurabh-7777 will u be raising PR back for this issue?

**Pull request closed without merging**
