### PR TITLE
Update: solution for [Day 27] in [Python] language to run with python v3

### PR DESCRIPTION
**Pull request by osoba**
day 27 in issue #4

### CODE REVIEW

**Comment by sagarchoudhary96** [comment]
@osoba , looks like the Day27 question is updated , you can check it out at hackerrank and update it accordingly?

**Comment by osoba** [comment]
@sagarchoudhary96 done (assuming this is the correct problem https://www.hackerrank.com/challenges/30-testing/problem )

**Comment by sagarchoudhary96** [comment]
hey @osoba i see two commit in this PR, can you remove the first commit as those changes won't be of any use.

**Comment by osoba** [comment]
@sagarchoudhary96 done

**Comment by sagarchoudhary96** [comment]
thanks @osoba :)

**Pull request merged**
