### PR TITLE
Add: solution for [Day 9] in [GoLang] language 

### PR DESCRIPTION
**Pull request by garvita-jain**

### CODE REVIEW

**Comment by garvita-jain** [comment]
Hi! I am getting lost here. I don't know how to create a new pull request for GoLang solution of Day10. Please help.

**Comment by sagarchoudhary96** [comment]
I see multiple commit which include commit for your python changes to and Day10 solution commit too. 

when you are working with different issues and want to raise separate PR. what you can do is create 
different branches for each and raise pr for those branches. so for e.g if you want to send PR for day 4 you can create a branch from master called day4-soln-branch and then commit in that branch with your changes and then can raise PR for it similarly for others too.
Screenshot 2019-10-02 at 1 10 01 PM

**Comment by garvita-jain** [comment]
Okay. Will do. Thanks

**Comment by sagarchoudhary96** [comment]
@garvita-jain  any update on this?

**Comment by garvita-jain** [comment]
Yes, I am working on this issue.
Will make corrections by today itself.

**Comment by sagarchoudhary96** [comment]
@garvita-jain is it done ?

**Comment by sagarchoudhary96** [comment]
@garvita-jain will you be doing these ?

**Pull request closed without merging**
