### PR TITLE
Update: solution for [Day 3] in [Python] Language to run with python v3

### PR DESCRIPTION
**Pull request by sargamm**
I have made changes in the day 3 python file for compatibility with python3 . Please have a look. Thanks!

### CODE REVIEW

**Comment by sagarchoudhary96** [comment]
@sargamm  I have added contributing guidelines in the repository. Request you to go through it and create/update PR as per the guidelines.

**Comment by sagarchoudhary96** [comment]
@sargamm you need to update the commit message as per the guideline and update PR. you can read about changing commit message here: https://help.github.com/en/articles/changing-a-commit-message 
Assigning this day3 question to you

**Comment by sagarchoudhary96** [comment]
@sargamm any updates on this or should i go ahead and give it to someone to work on?

**Comment by sagarchoudhary96** [comment]
@sargamm , it's fine no issues , just needed an update :), take your time

**Comment by sagarchoudhary96** [comment]
As you can see you commit message is still same you just updated Title of the Pr. you can go through https://help.github.com/en/articles/changing-a-commit-message link to know about how to change commit message
Screenshot 2019-10-02 at 12 34 04 PM

**Comment by sargamm** [comment]
This link is about changing a commit message using command line. Can you tell how can I change it on the website itself?

**Comment by sagarchoudhary96** [comment]
you can do it via command line only.

**Comment by sargamm** [comment]
I have made the required changes now. Please have a look

**Pull request merged**
