### PR TITLE
Update: solution for [Day 1] in [Python] to run with python v3.

### PR DESCRIPTION
**Pull request by alexandersperling**
Update: solution for [Day 1] in [Python] lanuage to run with python v3.

### CODE REVIEW

**Comment by sagarchoudhary96** [comment]
@alexandersperling , you need to update your commit message as per `contributing` guidelines. please refer to it and update Pr accordingly.

**Comment by alexandersperling** [comment]
@sagarchoudhary96 I updated the commit message accordingly. However from your contributing guideline it says to add a proper commit message and list examples, if you want exactly those commit messages that guideline should say this.

**Comment by sagarchoudhary96** [comment]
@alexandersperling , it's already in contributing guideline.
Screenshot 2019-10-02 at 7 23 04 PM

**Comment by sagarchoudhary96** [comment]
@alexandersperling as per your commit changes, you changed in print from `i+j` to `j+j` and similarly for other. those are not required to be changed. `i, d, s` are predefined in this hacker rank problem in stubbed code. please change them accordingly. and test out your solution on hackerrank here: https://www.hackerrank.com/challenges/30-data-types/problem
Screenshot 2019-10-02 at 7 28 56 PM

Screenshot 2019-10-02 at 7 27 48 PM

**Pull request merged**
