### PR TITLE
Add solution for Day 2 in Swift language

### PR DESCRIPTION
**Pull request by kristoft**

### CODE REVIEW

**Comment by sagarchoudhary96** [comment]
@kristoft  i ran your code on hackerrank but it failed. request you to test it out and update accordingly.
Screenshot 2019-10-03 at 6 49 41 PM

**Comment by kristoft** [comment]
@sagarchoudhary96 ok, i'll do!

**Comment by sagarchoudhary96** [comment]
@kristoft any updates?

**Comment by kristoft** [comment]
@sagarchoudhary96 Just pushed fixed version!

**Pull request merged**
