### PR TITLE
Move:  python solutions to python 3

### PR DESCRIPTION
**Pull request by navyakanu**

### CODE REVIEW

**Comment by navyakanu** [comment]
#4

**Comment by sagarchoudhary96** [comment]
@navyakanu , I have added contributing guidelines in the repository. Request you to go through it and create new PR as per the guidelines. Closing This PR for now.

**Comment by navyakanu** [comment]
@sagarchoudhary96 I have updated the PR, changed the commit name, kindly review and let me know if there are any comments which needs amends

**Comment by sagarchoudhary96** [comment]
@navyakanu there is merge conflict with your PR, resolve the conflict and Update the PR. you can resolve by syncing your forked repo with this repository. you can read about it by searching for `sync forked repo with main repo` on google search.

**Comment by sagarchoudhary96** [comment]
Also, at max only send PR for only 4 solutions.

**Comment by sagarchoudhary96** [comment]
@navyakanu , the solution for Day2 is already completed. check the issue first comment to see opened questions. Closing the PR.

**Pull request closed without merging**
