### PR TITLE
Created Solution.rs for Day 11

### PR DESCRIPTION
**Pull request by IvanFLeon**

### CODE REVIEW

**Comment by sagarchoudhary96** [comment]
@IvanFLeon I ran your code on hackerrank and it's throwing an error. request you to test it out on hackerrank and update the solution accordingly.
Screenshot 2019-10-11 at 8 16 22 AM

**Comment by IvanFLeon** [comment]
My bad, I didn't check the input format. It is working now :)!

**Comment by sagarchoudhary96** [comment]
@IvanFLeon  just a small change required, request you to update the commit message as per the contributing guidelines. you can read about it here : https://help.github.com/en/articles/changing-a-commit-message

**Comment by IvanFLeon** [comment]
Done! I've changed the commit messages now

**Pull request merged**
