### PR TITLE
Added solution for day 4 in go lang

### PR DESCRIPTION
**Pull request by Jolly1234**
Solution for Day 4 in go lang.

### CODE REVIEW

**Comment by sagarchoudhary96** [comment]
@Jolly1234  i see multiple commits here in this. make sure to send separate PR for Day 4 solution and other PR for readme updates. also, it will be great if you can squash all your readme commit into one.

**Comment by Jolly1234** [comment]
@sagarchoudhary96 updated. :)

**Comment by sagarchoudhary96** [comment]
hey I see 10 commits in this PR. if you are facing updating PR let me know or you can go ahead creating new PR with only 1 comment for Day 4 solution. and separate PR for Readme. Also when you can working with different issues for want to raise separate PR. what you can do is create different branches for each and raise pr for those branches. so for e.g if you want to send PR for day 4 you can create a branch from master  called day4-soln-branch and then commit in that branch with your changes and then can raise PR for it similarly for others too.
Screenshot 2019-10-02 at 12 20 24 PM

**Comment by Jolly1234** [comment]
Hi @sagarchoudhary96, yeah there are 10 commits but the ultimate file changed is one only for each of the PR. we can't do anything with commit history. Since file added/modified is only one with each so is that an issue? if u want I can create a new one but just asking like the ultimate file modified is one only.

**Comment by Jolly1234** [comment]
I am trying to update PR but commit history is going to maintain everything but files changed is only one. so with each PR only one addition is there. commit history is containing the addition/removal of files. 

git

**Comment by Jolly1234** [comment]
Can you close all the earlier PRs. I created new for all the issues.

**Pull request closed without merging**
