### PR TITLE
Added: Day10 solution in GoLang

### PR DESCRIPTION
**Pull request by garvita-jain**

### CODE REVIEW

**Comment by sagarchoudhary96** [comment]
@garvita-jain  this PR contains Day9 file changes also. to request you to create PR  only for Day10 here. you can create a new branch from master and make a commit for Day10 in that branch and create PR with that branch.

**Comment by sagarchoudhary96** [comment]
@garvita-jain can you update it ?

**Comment by sagarchoudhary96** [comment]
@garvita-jain any updates for this onee ?

**Comment by sagarchoudhary96** [comment]
hey @garvita-jain, request you to update about this.

**Comment by garvita-jain** [comment]
I have made another pull request. Please review it.

**Pull request closed without merging**
