### PR TITLE
Update: solution for [Day 14] in [Python] language to run with python v3.

### PR DESCRIPTION
**Pull request by narain1**
Update: solution for [Day 14] in [Python] language to run with python v3.

### CODE REVIEW

**Comment by sagarchoudhary96** [comment]
@narain1 request you to update Commit message as per the **Contribution Guidelines** defined for all the 4 PR's.

**Comment by narain1** [comment]
I have no idea about that can you help me

**Comment by sagarchoudhary96** [comment]
@narain1 you can go through this link: https://help.github.com/en/articles/changing-a-commit-message

Hope it helps, let me know in case you still face any problem.

**Comment by narain1** [comment]
is this change to commit message okay

**Comment by sagarchoudhary96** [comment]
@narain1 check the contribution guideline in this repository to see what commit message should look like. You need to update as per that.

**Comment by narain1** [comment]
I guess its done

**Comment by sagarchoudhary96** [comment]
@narain1 you changed the PR title not the commit message the commit message is still `update Solution.py`.
use  this : https://help.github.com/en/articles/changing-a-commit-message  to know how to change the commit message.

**Pull request closed without merging**
