### PR TITLE
Update : README.md

### PR DESCRIPTION
**Pull request by Jolly1234**

### CODE REVIEW

**Comment by sagarchoudhary96** [comment]
hey @Jolly1234 , for readme can you update it to look like as it is in screenshot. this will look better. 3 in each row. 10 in each column. i.e 0-9 in first column 10-19 in second and 20-29 in third column.
And this will be heading 

`### The following is the list of problem statements and solutions:-`
Screenshot 2019-10-02 at 5 16 09 PM

**Comment by Jolly1234** [comment]
@sagarchoudhary96 yeah sure.

**Comment by sagarchoudhary96** [comment]
@Jolly1234  any updates?

**Comment by Jolly1234** [comment]
Hi not now.bit busy with something else.it would take time . Feel free to assign it to someone else.it would take some time from my side to finish it as I am currently busy with other stuff.

**Comment by sagarchoudhary96** [comment]
if anybody wants to take it up can go ahead and let me know.

**Comment by sagarchoudhary96** [comment]
closing PR as its completed by @rohit1636

**Pull request closed without merging**
