### PR TITLE
Making Day 4, 8, 13, and 16 compatible with Python 3. 

### PR DESCRIPTION
**Pull request by cjtaylor1990**
Most of this was making fairly small changes:

print -> print()
raw_input() -> input()
dictionary.has_key(key) -> key in dictionary

### CODE REVIEW

**Comment by sagarchoudhary96** [comment]
@cjtaylor1990 , request  you to check contributing guidelines and update commit message accordingly.

**Comment by cjtaylor1990** [comment]
@sagarchoudhary96 Updated the commit message

**Comment by sagarchoudhary96** [comment]
@cjtaylor1990 the solution for day 8 is not working as the while loop is waiting for input even when EOF is reached. request you to update solution for day 8 to pass all testcases on hackerrank and then update PR with the updated solution for day8.
Screenshot 2019-10-05 at 9 51 58 PM

**Comment by cjtaylor1990** [comment]
Well, that error was in the original code, as raw_input() isn't in my script. I'll fix it though. The issue lies in using the infinite while loop with the break condition. You'll need a different method to read things in. I already solved this problem on Hacker Rank, so expect it soon.

**Comment by cjtaylor1990** [comment]
There, fixed it. The issue is that you can't do that infinite while loop with break in either language on Hacker Rank without getting an EOF error.

**Pull request merged**
